### ISSUE TITLE
Ignore URLs which might be wrongly labeled as misspellings

### ISSUE THREAD

**Issue by cbrevik** [varianter/probot-spellchecker#28]
Same as #27, but also ignore URLs

**Comment by tjolr** [comment]
Hi @cbrevik ! 
My previous build failed in travis because of this command: "eval yarn --frozen-lockfile " failed. Found a solution which was to add "install: - yarn" to the travis.yml - file.
After doing that i got a new error that Vercel engine "node" wasn't compatible with version lower than 10, and the travis.yml was set to 8.3. So after setting the node version to 10.1 in travis.yml my build passed.

I see that the two previous Pull Requests (#29 & #30 ) failed because of the same issues, so I think they will pass as well if they get re-run with the new travis.yml updates :) 

Let me know if i should change this or anything else?

**Comment by cbrevik** [comment]
No that seems fine to me! I'll look them over now. Thanks :D
